version: '3.8'

services:
  # Define o serviço do Redis.
  redis:
    image: redis:latest
    container_name: redis
    ports:
      # Mapeia a porta 6379 do host para a 6379 do container.
      - "6379:6379"
    networks:
      - ratelimiter-net

  # Define o serviço da nossa aplicação Go.
  app:
    build: . # Constrói a imagem a partir do Dockerfile no diretório atual.
    container_name: rate-limiter-app
    ports:
      # Mapeia a porta 8080 do host para a 8080 do container.
      - "8080:8080"
    depends_on:
      - redis # Garante que o container do Redis inicie antes da nossa aplicação.
    networks:
      - ratelimiter-net

# Define a rede customizada que os containers usarão para se comunicar.
networks:
  ratelimiter-net:
    driver: bridge